global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.free.fr:25'
  smtp_from: 'alertmanager@max.org'
  smtp_require_tls: false


route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'team-X-mails'
  email_configs:
  - to: 'xxx+alerts@gmail.com'
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
